### ISSUE TITLE
Provide releases, packages and documentation for taskchampion/sync-server

### ISSUE THREAD

**Issue by jcgruenhage** [GothenburgBitFactory/taskchampion-sync-server#2]
As a user who used to use taskd, I want to have a self-hostable sync backend again. It seems to me like `taskchampion/sync-server` is that backend.

To me, it is not clear how I am supposed to go about this. I can find docs for for running that piece of software under https://taskchampion.github.io/taskchampion/running-sync-server.html, which comes from an archived repo (https://github.com/taskchampion/taskchampion).

Ideally, there'd be docs, release tags, container images and so on. I can manage to build some of these myself if needed, but at least I need release tags to know where to grab the source from.

**Comment by ogarcia** [comment]
@djmitche Yes, today during the day I will do a PR with the Dockerfile and a GitHub action to build the image on the GitHub remote. :wink:

**Comment by jcgruenhage** [comment]
@djmitche I've started some work on code for this on Saturday already, and will continue onwards in that new repo. You can expect a PR for that some time in the near-ish future ^^

**Comment by djmitche** [comment]
Thank you both!

**Comment by jcgruenhage** [comment]
I think with the code split out to a separate repo, a Dockerfile already PR'd and other bits being worked on over there, we can probably close this issue here, as it's not really the right place anymore, right?

**Comment by djmitche** [comment]
I moved the issue to the new repo! But, yes, I think we can close tihs.
